version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mosquitto
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
    volumes:
      - .:/app
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883" # Porta para conexões MQTT
      - "9001:9001" # Porta para WebSocket (opcional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:
